export const companyActionTypes = {
    SET_COMPANY: 'SET_COMPANY',
    SET_COMPANY_EMAILS: 'SET_COMPANY_EMAILS',
    SET_COMPANY_PHONENUMBERS: 'SET_COMPANY_PHONENUMBERS',
    SET_COMPANY_RESPONSIBLE: 'SET_COMPANY_RESPONSIBLE',
};
