export const searchActionTypes = {
    SET_SEARCH_SUGGESTIONS: 'SET_SEARCH_SUGGESTIONS',
    SET_SELECTED_ALL: 'SET_SELECTED_ALL',
    SET_SELECTED_CARS: 'SET_SELECTED_CARS',
    SET_SELECTED_CONTACTS: 'SET_SELECTED_CONTACTS',
    SET_SELECTED_KONCERN_COMPANIES: 'SET_SELECTED_KONCERN_COMPANIES',
};
