export const fleetActionTypes = {
    SET_FLEET: 'SET_FLEET',
    SET_FLEET_HISTORIC: 'SET_FLEET_HISTORIC',
    SET_FLEET_HISTORIC_LOADING: 'SET_FLEET_HISTORIC_LOADING',
    SET_FLEET_LOADING: 'SET_FLEET_LOADING',
};
