export const personActionTypes = {
    SET_PERSON: 'SET_PERSON',
    SET_PERSON_CONSENT: 'SET_PERSON_CONSENT',
    SET_PERSON_DEALS: 'SET_PERSON_DEALS',
    SET_PERSON_EMAILS: 'SET_PERSON_EMAILS',
    SET_PERSON_PHONENUMBERS: 'SET_PERSON_PHONENUMBERS',
    SET_PERSON_RESPONSIBLE: 'SET_PERSON_RESPONSIBLE',
};
