export default {
    activity: 'Aktivitet',
    agile: 'Bearbeta',
    aboutUs: 'Om oss',
    calendar: 'Kalender',
    companyInfo: 'Företagsinformation',
    contact: 'Kontakt',
    contactInfo: 'Kontaktinformation',
    createNewPassword: 'Skapa nytt lösenord',
    emailNotifications: 'E-post notifikationer',
    home: 'Hem',
    lists: 'Listor',
    login: 'Inloggning',
    logon: 'Logga in',
    logout: 'Logga ut',
    news: 'Nyheter',
    ourService: 'Vår tjänst',
    prices: 'Priser',
    prospect: 'Prospektera',
    savePassword: 'Spara lösenord',
    searchPlaceholder: 'Sök fordon eller fordonsbrukare...',
    settings: 'Inställningar',
    settingsPasswordHintEmpty: 'Lösenord kan ej vara tomma',
    settingsPasswordHintNotMatching: 'Lösenorden överensstämmer ej',
    settingsPasswordHintSaved: 'Nytt lösenord sparat',
    team: 'Team',
}
