export default {
    aboutUs: 'Om oss',
    activities: 'Aktiviteter',
    activity: 'Aktivitet',
    agile: 'Bearbeta',
    analyse: 'Analysera',
    calendar: 'Kalender',
    calendarMonths: {
        1: 'Januari',
        2: 'Februari',
        3: 'Mars',
        4: 'April',
        5: 'Maj',
        6: 'Juni',
        7: 'Juli',
        8: 'Augusti',
        9: 'September',
        10: 'Oktober',
        11: 'November',
        12: 'December',
    },
    companyInfo: 'Företagsinformation',
    contact: 'Kontakt',
    contactInfo: 'Kontaktinformation',
    created: 'Skapad',
    createNewPassword: 'Skapa nytt lösenord',
    edit: 'Redigera',
    emailNotifications: 'E-post notifikationer',
    home: 'Hem',
    lists: 'Listor',
    login: 'Inloggning',
    logon: 'Logga in',
    logout: 'Logga ut',
    news: 'Nyheter',
    newsSub: 'Detta har hänt på Bilprospekt.se',
    ourService: 'Vår tjänst',
    plannedActivities: 'Planerade aktiviteter',
    prices: 'Priser',
    prospect: 'Prospektera',
    responsible: 'Ansvarig',
    savedInList: 'Sparad i lista',
    savePassword: 'Spara lösenord',
    search: 'Sök',
    searchPlaceholder: 'Sök fordon eller fordonsbrukare...',
    settings: 'Inställningar',
    settingsPasswordHintEmpty: 'Lösenord kan ej vara tomma',
    settingsPasswordHintNotMatching: 'Lösenorden överensstämmer ej',
    settingsPasswordHintSaved: 'Nytt lösenord sparat',
    status: 'Status',
    team: 'Team',
}
