export default {
    aboutUs: 'Om oss',
    action: 'Händelse',
    activities: 'Aktiviteter',
    activitiesComingUp: 'Ej utförda aktiviteter',
    activity: 'Aktivitet',
    add: 'Lägg till',
    addComment: 'Lägg till kommentar',
    addConnectionsToDeal: 'Lägg till kopplingar',
    addDescription: 'Lägg till beskrivning',
    addEmail: 'Lägg till e-post',
    addFile: 'Bifoga fil',
    addName: 'Lägg till namn',
    addPhone: 'Lägg till telefonnummer',
    addToList: 'Spara till lista',
    address: 'Adress',
    agile: 'Bearbeta',
    allActivitiesAllIncludingComments: 'Alla händelser och kommentarer',
    analyse: 'Analysera',
    analysis: 'Behovsanalys',
    and: 'Och',
    at: 'Hos',
    branch: 'Bransch',
    brand: 'Märke',
    boughtPlace: 'Inköpsplats',
    calendar: 'Kalender',
    calendarMonths: {
        1: 'Januari',
        2: 'Februari',
        3: 'Mars',
        4: 'April',
        5: 'Maj',
        6: 'Juni',
        7: 'Juli',
        8: 'Augusti',
        9: 'September',
        10: 'Oktober',
        11: 'November',
        12: 'December',
    },
    call: 'Samtal',
    cancel: 'Avbryt',
    cars: 'Fordon',
    carsHowTo: 'Sök upp och koppla fordon med hjälp av sökrutan. Ta bort kopplingen till ett fordon genom att klicka på papperskorgen.',
    changeOwner: 'Ändra ansvarig',
    changedOwner: 'Ändrad ansvarig',
    changesSaved: 'Ändringar sparade',
    cold: 'Kall',
    comment: 'Kommentar',
    comments: 'Kommentarer',
    company: 'Företag',
    companies: 'Företag',
    companyInfo: 'Företagsinformation',
    companyName: 'Företagsnamn',
    complete: 'Utförd',
    completeEvent: 'Aktivitet utförd',
    connectCars: 'Koppla fordon',
    connectContacts: 'Koppla kontaktpersoner',
    connectedTo: 'Kopplad till',
    connection: 'Koppling',
    connectKoncernCompanies: 'Koppla företag inom koncern',
    connectProspects: 'Koppla prospekt',
    contact: 'Kontakt',
    contacts: 'Kontaktpersoner',
    contacted: 'Behov undersöks',
    contactHowTo: 'Sök upp kontakter med hjälp av sökrutan, eller skapa ny kontakt genom att klicka på plustecknet. Ta bort en kontakt genom att klicka på pennan för att redigera kontakten, och sedan på papperskorgen för att ta bort den.',
    contactInfo: 'Kontaktinformation',
    contactWasRemoved: 'Kontakten har tagits bort',
    contactWasSaved: 'Ny kontakt sparad',
    contactWasUpdated: 'Kontakten har ändrats',
    couldNotCreateDeal: 'Kunde ej skapa affär',
    couldNotGetDeal: 'Kunde ej hämta affär',
    created: 'Skapad',
    createNewContact: 'Skapa ny kontakt',
    createNewDeal: 'Skapa ny affär',
    createNewPassword: 'Skapa nytt lösenord',
    dataMissing: 'Uppgift saknas',
    date: 'Datum',
    dateAcquired: 'Inköpsdatum',
    dateSold: 'Försäljningsdatum',
    deal: 'Affär',
    dealName: 'Namn på affär',
    dealPotential: 'Potential (antal fordon el. dyl.)',
    dealWasCreated: 'Affär har blivit skapad',
    dealWasUpdated: 'Affären är nu uppdaterad',
    description: 'Beskrivning',
    didCall: 'Har ringt',
    didEmail: 'Har e-postat',
    didLosePrice: 'Förlorade affären pga. pris',
    didLoseProduct: 'Förlorade affären pga. produkten',
    didLoseUnknown: 'Förlorade affären pga. okänd anledning',
    didLoseWindow: 'Förlorade affären pga. prospektet inte var i köpfönstret',
    didMail: 'Har e-postat',
    didMeeting: 'Har haft möte',
    didPost: 'Har skickat brev',
    doVehicleSearch: 'Gör fordonssökning',
    download: 'Ladda ner',
    edit: 'Redigera',
    editComment: 'Redigera kommentar',
    editContact: 'Redigera kontakt',
    editDeal: 'Redigera affär',
    email: 'E-post',
    emailNotifications: 'E-post notifikationer',
    entityWasAddedToContact: 'Koppling till kontakt har skapats',
    entityWasRemovedFromContact: 'Kopplingen för kontakt har tagits bort',
    events: 'Planerade aktiviteter',
    eventsCalendar: 'Kalendervy',
    eventsFlow: 'Flödesvy',
    female: 'Kvinna',
    files: 'Filer',
    filesHowTo: 'Ladda upp filer med hjälp av plustecknet. Ta bort filer genom att klicka på papperskorgen som visas när muspekaren förs över en fil.',
    fleet: 'Vagnpark',
    fleetHistoric: 'Historisk vagnpark',
    for: 'För',
    from: 'Från',
    gender: 'Kön',
    genderNotProvided: 'Kön ej angivet',
    handleCars: 'Hantera fordon som är kopplade till affären',
    handleContacts: 'Hantera kopplade kontaktpersoner',
    handleFiles: 'Hantera uppladdade filer',
    handleProspects: 'Hantera prospekt som är kopplade till affären',
    hideConnectCars: 'Dölj koppla fordon',
    hideConnectContacts: 'Dölj koppla kontaktpersoner',
    hideConnectProspects: 'Dölj koppla prospekt',
    home: 'Hem',
    hot: 'Het',
    iceCold: 'Iskall',
    idle: 'Prospekt',
    imgTextLogo: 'Bilprospekt logotyp',
    info: 'Information',
    koncernCompany: 'Koncernbolag',
    lastUpdate: 'Senast uppdaterad',
    lists: 'Listor',
    load: 'Ladda fler',
    login: 'Inloggning',
    logon: 'Logga in',
    logout: 'Logga ut',
    lost: 'Förlorad',
    lukewarm: 'Ljummen',
    mail: 'E-post',
    male: 'Man',
    maturity: 'Sannolikhet',
    maximize: 'Maximera',
    meeting: 'Möte',
    minimize: 'Minimera',
    model: 'Modell',
    move: 'Flytta',
    moved: 'Flyttade',
    name: 'Namn',
    navigateBefore: 'Bakåt',
    navigateNext: 'Framåt',
    navigateToCar: 'Gå till fordon',
    navigateToProspect: 'Gå till prospekt',
    negotiation: 'Under förhandling',
    news: 'Nyheter',
    newsSub: 'Detta har hänt på Bilprospekt.se',
    noActivity: 'Aktivitet saknas',
    noContactConnections: 'Inga kontakter kopplade till affär',
    noContacts: 'Kontakter saknas',
    noEvents: 'Ingen planerad aktivitet',
    noFiles: 'Inga uppladdade filer',
    noName: 'Namn saknas',
    noOwner: 'Ansvarig saknas',
    noProspectConnections: 'Inga prospekt kopplade till affär',
    noProspects: 'Prospekt saknas',
    notProvided: 'Ej angivet',
    noVehicleConnections: 'Inga fordon kopplade till affär',
    noVehicles: 'Fordon saknas',
    numberOfDeals: 'Antal affärer',
    offer: 'Offert',
    offert: 'Offert',
    on: 'På',
    onDeal: 'På affär',
    oneProspect: 'Prospekt',
    openInAgile: 'Öppna i Bearbeta',
    orgNr: 'Organisationsnummer',
    other: 'Övrigt',
    ourService: 'Vår tjänst',
    owner: 'Ansvarig',
    parentCompany: 'Moderbolag',
    partOfDeals: 'Koppling till affärer',
    partOfKoncern: 'Ingår i en koncern',
    phone: 'Telefon',
    phoneNumbers: 'Telefonnummer',
    placeholderSearchAll: 'Sök person, företag eller registreringsnummer',
    placeholderSearchCars: 'Sök fordon av denna brukare',
    placeholderSearchKoncernCompanies: 'Sök företag inom koncern',
    placeholderSearchContacts: 'Sök kontakt',
    postAddress: 'Utdelningsadress',
    potential: 'Potential',
    prices: 'Priser',
    prospect: 'Prospektera',
    prospects: 'Prospekt',
    prospectsHowTo: 'Sök upp och koppla prospekt med hjälp av sökrutan. Ta bort kopplingen till ett prospekt genom att klicka på papperskorgen som visas när muspekaren förs över en rad.',
    regarding: 'Gällande',
    regret: 'Återställ',
    regNumber: 'Registreringsnummer',
    remove: 'Ta bort',
    removeCar: 'Ta bort fordon',
    removeComment: 'Ta bort kommentar',
    removeContact: 'Radera kontakt',
    removeEnsure: 'Är du säker?',
    removeEntityFromContact: 'Ta bort kontaktens koppling till detta objekt',
    removeEvent: 'Ta bort planerad aktivitet',
    removeProspect: 'Ta bort prospekt',
    save: 'Spara',
    saveChanges: 'Spara ändringar',
    saveContact: 'Spara ny kontakt',
    savedInList: 'Sparad i lista',
    savePassword: 'Spara lösenord',
    search: 'Sök',
    settings: 'Inställningar',
    settingsPasswordHintEmpty: 'Lösenord kan ej vara tomma',
    settingsPasswordHintNotMatching: 'Lösenorden överensstämmer ej',
    settingsPasswordHintSaved: 'Nytt lösenord sparat',
    showing: 'Visar',
    status: 'Status',
    team: 'Team',
    theDeal: 'Affären',
    theTeam: 'Vi som jobbar här',
    testride: 'Provkörning',
    time: 'Tid',
    to: 'Till',
    todo: 'I kontakt',
    toggleComments: 'Visa/dölj kommenterar',
    toggleMoved: 'Visa/dölj förflyttningar',
    toggleOff: 'Av',
    toggleOn: 'På',
    trash: 'Borttagen',
    type: 'Typ',
    unknown: 'Okänd',
    uploadFile: 'Ladda upp fil',
    user: 'Användare',
    valuation: 'Värdering',
    valueAlreadyExists: 'Detta värde existerar redan',
    valueCannotBeEmpty: 'Värde kan ej vara tomt',
    vehicle: 'Fordon',
    vehicles: 'Fordon',
    veryHot: 'Stekhet',
    visit: 'Kundbesök',
    visitingAddress: 'Besöksadress',
    willCall: 'Skall ringa',
    willEmail: 'Skall e-posta',
    willMail: 'Skall e-posta',
    willMeeting: 'Skall ha möte',
    willPost: 'Skall skicka brev',
    with: 'Med',
    won: 'Vunnen',
    years: 'År',
    zipMuncipality: 'Postort'
}
