export default {
    aboutCompany: 'Om företag',
    aboutKoncern: 'Om koncern',
    aboutPerson: 'Om person',
    aboutUs: 'Om oss',
    acquiredAges: 'Innehavstid',
    action: 'Händelse',
    activated: 'Aktiverat',
    activities: 'Aktiviteter',
    activitiesComingUp: 'Ej utförda aktiviteter',
    activity: 'Aktivitet',
    add: 'Lägg till',
    addComment: 'Lägg till kommentar',
    addConnectionsToDeal: 'Lägg till kopplingar',
    addDescription: 'Lägg till beskrivning',
    addEmail: 'Lägg till e-post',
    addFile: 'Bifoga fil',
    addName: 'Lägg till namn',
    aPiece: 'St',
    addPhone: 'Lägg till telefonnummer',
    addToList: 'Spara till lista',
    address: 'Adress',
    age: 'Ålder',
    agile: 'Bearbeta',
    allActivitiesAllIncludingComments: 'Alla händelser och kommentarer',
    amount: 'Antal',
    amountKoncernCompanies: 'Antal koncernbolag',
    amountVehicles: 'Antal fordon',
    analyse: 'Analysera',
    analysis: 'Behovsanalys',
    and: 'Och',
    at: 'Hos',
    atv: 'Fyrhjuling',
    ATV: 'ATV',
    branch: 'Bransch',
    brand: 'Märke',
    brands: 'Märken',
    bilprospekt: 'Bilprospekt',
    bought: 'Köpt',
    boughtPlace: 'Inköpsplats',
    bu: 'Buss',
    BU: 'BU',
    calendar: 'Kalender',
    calendarMonths: {
        1: 'Januari',
        2: 'Februari',
        3: 'Mars',
        4: 'April',
        5: 'Maj',
        6: 'Juni',
        7: 'Juli',
        8: 'Augusti',
        9: 'September',
        10: 'Oktober',
        11: 'November',
        12: 'December',
    },
    call: 'Samtal',
    cancel: 'Avbryt',
    carBody: 'Kaross',
    cars: 'Fordon',
    carsHowTo: 'Sök upp och koppla fordon med hjälp av sökrutan. Ta bort kopplingen till ett fordon genom att klicka på papperskorgen.',
    carYear: 'Fordonsår',
    cashLiquidity: 'Kassalikviditet',
    changeOwner: 'Ändra ansvarig',
    changedOwner: 'Ändrad ansvarig',
    changesSaved: 'Ändringar sparade',
    chooseColumn: 'Välj kolumn',
    chooseEnglishLanguage: 'Välj språk: engelska',
    chooseNewPassword: 'Välj nytt lösenord',
    chooseSwedishLanguage: 'Välj språk: svenska',
    chosenLanguage: 'Valt språk',
    cold: 'Kall',
    comment: 'Kommentar',
    comments: 'Kommentarer',
    company: 'Företag',
    companies: 'Företag',
    companyName: 'Företagsnamn',
    complement: 'Komplettering',
    complete: 'Utförd',
    completeEvent: 'Aktivitet utförd',
    connectCars: 'Koppla fordon',
    connectContacts: 'Koppla kontaktpersoner',
    connectedTo: 'Kopplad till',
    connection: 'Koppling',
    connectKoncernCompanies: 'Koppla koncern-företag',
    connectProspects: 'Koppla prospekt',
    contact: 'Kontakt',
    contacts: 'Kontaktpersoner',
    contacted: 'Behov undersöks',
    contactHowTo: 'Sök upp kontakter med hjälp av sökrutan, eller skapa ny kontakt genom att klicka på plustecknet. Ta bort en kontakt genom att klicka på pennan för att redigera kontakten, och sedan på papperskorgen för att ta bort den.',
    contactInfo: 'Kontaktinformation',
    contactWasRemoved: 'Kontakten har tagits bort',
    contactWasSaved: 'Ny kontakt sparad',
    contactWasUpdated: 'Kontakten har ändrats',
    couldNotCreateDeal: 'Kunde ej skapa affär',
    couldNotGetDeal: 'Kunde ej hämta affär',
    couldNotSaveToList: 'Kunde ej spara till lista',
    created: 'Skapad',
    createdBy: 'Skapad av',
    createNewContact: 'Skapa ny kontakt',
    createNewDeal: 'Skapa ny affär',
    createNewList: 'Skapa ny lista',
    dataMissing: 'Uppgift saknas',
    date: 'Datum',
    dateAcquired: 'Inköpsdatum',
    dateSold: 'Försäljningsdatum',
    deal: 'Affär',
    dealName: 'Namn på affär',
    dealPotential: 'Potential (antal fordon el. dyl.)',
    dealWasCreated: 'Affär har blivit skapad',
    dealWasUpdated: 'Affären är nu uppdaterad',
    description: 'Beskrivning',
    didCall: 'Har ringt',
    didEmail: 'Har e-postat',
    didLosePrice: 'Förlorade affären pga. pris',
    didLoseProduct: 'Förlorade affären pga. produkten',
    didLoseUnknown: 'Förlorade affären pga. okänd anledning',
    didLoseWindow: 'Förlorade affären pga. prospektet inte var i köpfönstret',
    didMail: 'Har e-postat',
    didMeeting: 'Har haft möte',
    didPost: 'Har skickat brev',
    disabled: 'Inaktiverat',
    doVehicleSearch: 'Gör fordonssökning',
    download: 'Ladda ner',
    edit: 'Redigera',
    editComment: 'Redigera kommentar',
    editContact: 'Redigera kontakt',
    editDeal: 'Redigera affär',
    email: 'E-post',
    emailNotifications: 'E-post notifikationer',
    en: 'Engelska',
    entityWasAddedToContact: 'Koppling till kontakt har skapats',
    entityWasRemovedFromContact: 'Kopplingen för kontakt har tagits bort',
    events: 'Planerade aktiviteter',
    eventsCalendar: 'Kalendervy',
    eventsFlow: 'Flödesvy',
    existingLists: 'Existerande listor',
    exploreLeads: 'Undersök leads',
    exploreProspects: 'Undersök prospekt',
    female: 'Kvinna',
    files: 'Filer',
    filesHowTo: 'Ladda upp filer med hjälp av plustecknet. Ta bort filer genom att klicka på papperskorgen som visas när muspekaren förs över en fil.',
    financed: 'Finansisering',
    financedBy: 'Finansisering via',
    fleet: 'Vagnpark',
    fleetAnalysis: 'Vagnparksanalys',
    fleetAnalysisCharts: 'Vagnparksdata',
    fleetAnalysisChartsHistoric: 'Historisk vagnparksdata',
    fleetCurrent: 'Nuvarande vagnpark',
    fleetHistoric: 'Historisk vagnpark',
    for: 'För',
    from: 'Från',
    gdprConsent: 'GDPR-samtycke',
    gdprConsentInfo: 'Finns samtycke från denna brukare att spara personuppgifter',
    gender: 'Kön',
    genderNotProvided: 'Kön ej angivet',
    handleCars: 'Hantera fordon som är kopplade till affären',
    handleContacts: 'Hantera kopplade kontaktpersoner',
    handleFiles: 'Hantera uppladdade filer',
    handleProspects: 'Hantera prospekt som är kopplade till affären',
    haveOldCompanyOrder: 'Har ledningsuppgifter (äldre än en månad)',
    haveOldNameOrder: 'Har personuppgifter (äldre än en månad)',
    haveOldPhoneOrder: 'Har telefonnummer (äldre än en månad)',
    hb: 'Husbil',
    HB: 'HB',
    hideConnectCars: 'Dölj koppla fordon',
    hideConnectContacts: 'Dölj koppla kontaktpersoner',
    hideConnectProspects: 'Dölj koppla prospekt',
    holdingPeriod: 'Innehavsperiod',
    home: 'Hem',
    hot: 'Het',
    hv: 'Husvagn',
    HV: 'HV',
    iceCold: 'Iskall',
    idle: 'Prospekt',
    imgTextLogo: 'Bilprospekt logotyp',
    imgTextLogoKundprospekt: 'Kundprospekt logotyp',
    info: 'Information',
    is: 'Är',
    koncern: 'Koncern',
    koncernCompany: 'Koncernbolag',
    koncernStructure: 'Koncernstruktur',
    language: 'Språk',
    lastUpdate: 'Senast uppdaterad',
    lb: 'Lastbil',
    LB: 'LB',
    leads: 'Leads',
    leadsReceived: 'Inkomna leads till Bilprospekt',
    leadsType: 'Typ av lead',
    leadsWidgetHandle_1: 'Totalt finns det',
    leadsWidgetHandle_2: 'leads kvar att hantera',
    leadsWidgetNew_1: 'Det finns nu',
    leadsWidgetNew_2: 'nya leads att hantera',
    lists: 'Listor',
    load: 'Ladda fler',
    login: 'Inloggning',
    logon: 'Logga in',
    logout: 'Logga ut',
    lost: 'Förlorad',
    lukewarm: 'Ljummen',
    mail: 'E-post',
    male: 'Man',
    maturity: 'Sannolikhet',
    maximize: 'Maximera',
    mc: 'Motorcykel',
    MC: 'MC',
    meeting: 'Möte',
    minimize: 'Minimera',
    model: 'Modell',
    models: 'Modeller',
    monitoring: 'Bevakning',
    months: 'Månader',
    move: 'Flytta',
    moved: 'Flyttade',
    name: 'Namn',
    nameNewList: 'Namn på ny lista',
    navigateBefore: 'Bakåt',
    navigateNext: 'Framåt',
    navigateToCar: 'Gå till fordon',
    navigateToFleetAnalysis: 'Gå till vagnparksanalys',
    navigateToProspect: 'Gå till prospekt',
    negotiation: 'Under förhandling',
    netSales: 'Nettoomsättning',
    new: 'Ny',
    news: 'Nyheter',
    newsSub: 'Detta har hänt på Bilprospekt.se',
    noActivity: 'Aktivitet saknas',
    noContactConnections: 'Inga kontakter kopplade till affär',
    noContacts: 'Kontakter saknas',
    noDeals: 'Inga affärer',
    noEmployees: 'Antal anställda',
    noEvents: 'Ingen planerad aktivitet',
    noFiles: 'Inga uppladdade filer',
    noName: 'Namn saknas',
    noOwner: 'Ansvarig saknas',
    noProspectConnections: 'Inga prospekt kopplade till affär',
    noProspects: 'Prospekt saknas',
    notProvided: 'Ej angivet',
    noVehicleConnections: 'Inga fordon kopplade till affär',
    noVehicles: 'Fordon saknas',
    numberOfDeals: 'Antal affärer',
    of: 'Av',
    offer: 'Offert',
    offert: 'Offert',
    on: 'På',
    onDeal: 'På affär',
    oneProspect: 'Prospekt',
    openInAgile: 'Öppna i Bearbeta',
    ordered: 'Beställt',
    orderedCompany: 'Beställt ledningsuppgifter',
    orderedMailings: 'Beställt brevutskick',
    orderedName: 'Beställt personuppgifter',
    orderedPhone: 'Beställt telefonnummer',
    orgNr: 'Organisationsnummer',
    other: 'Övrigt',
    owner: 'Ansvarig',
    parentCompany: 'Moderbolag',
    partOfDeals: 'Koppling till affärer',
    partOfKoncern: 'Ingår i en koncern',
    pb: 'Personbil',
    PB: 'PB',
    phone: 'Telefon',
    phoneNumbers: 'Telefonnummer',
    placeholderSearchAll: 'Sök person, företag eller registreringsnummer',
    placeholderSearchCars: 'Sök fordon inom persons/företags/koncerns vagnpark',
    placeholderSearchKoncernCompanies: 'Sök företag inom koncern',
    placeholderSearchContacts: 'Sök kontakt',
    placeholderSearchTable: 'Sök i tabell',
    person: 'Person',
    postAddress: 'Utdelningsadress',
    potential: 'Potential',
    prices: 'Priser',
    privatePerson: 'Privatperson',
    prospect: 'Prospektera',
    prospects: 'Prospekt',
    prospectsHowTo: 'Sök upp och koppla prospekt med hjälp av sökrutan. Ta bort kopplingen till ett prospekt genom att klicka på papperskorgen som visas när muspekaren förs över en rad.',
    received: 'Inkommen',
    regarding: 'Gällande',
    regret: 'Återställ',
    regNumber: 'Registreringsnummer',
    regNumberShort: 'Reg nr',
    regYear: 'Registreringsår',
    remove: 'Ta bort',
    removeCar: 'Ta bort fordon',
    removeComment: 'Ta bort kommentar',
    removeContact: 'Radera kontakt',
    removeEnsure: 'Är du säker?',
    removeEntityFromContact: 'Ta bort kontaktens koppling till detta objekt',
    removeEvent: 'Ta bort planerad aktivitet',
    removeProspect: 'Ta bort prospekt',
    resefinintokost: 'Res. e. finansnetto (TKR)',
    rowsPerPage: 'Rader per sida',
    save: 'Spara',
    saveChanges: 'Spara ändringar',
    saveContact: 'Spara ny kontakt',
    savedInList: 'Sparad i lista',
    savePassword: 'Spara lösenord',
    search: 'Sök',
    sellerName: 'Inköpsplats',
    settings: 'Inställningar',
    settingsPasswordHintEmpty: 'Lösenord kan ej vara tomma',
    settingsPasswordHintNotMatching: 'Lösenorden överensstämmer ej',
    settingsPasswordHintSaved: 'Nytt lösenord sparat',
    showing: 'Visar',
    sold: 'Såld',
    solidity: 'Soliditet',
    ss: 'Snöskoter',
    SS: 'SS',
    status: 'Status',
    submitted: 'Utlagd',
    subscription: 'Prenumeration',
    subscriptionPossible: 'Prenumeration möjlig',
    supertemp: 'Fordon ute för försäljning',
    supertempWidgetHandle_1: 'Totalt finns det',
    supertempWidgetHandle_2: 'Brukare som ska byta fordon kvar att hantera',
    supertempWidgetNew_1: 'Senast dygnet har',
    supertempWidgetNew_2: 'Brukare lagt ut fordon till försäljning',
    sv: 'Släpvagn',
    SV: 'SV',
    swe: 'Svenska',
    team: 'Team',
    theDeal: 'Affären',
    theTeam: 'Vi som jobbar här',
    testride: 'Provkörning',
    time: 'Tid',
    tlb: 'Tung lastbil',
    TLB: 'TLB',
    to: 'Till',
    todo: 'I kontakt',
    toggleComments: 'Visa/dölj kommenterar',
    toggleMoved: 'Visa/dölj förflyttningar',
    toggleOff: 'Av',
    toggleOn: 'På',
    total: 'Totalt',
    trash: 'Borttagen',
    type: 'Typ',
    unknown: 'Okänd',
    uploadFile: 'Ladda upp fil',
    used: 'Begagnad',
    user: 'Användare',
    valuation: 'Värdering',
    valueAlreadyExists: 'Detta värde existerar redan',
    valueCannotBeEmpty: 'Värde kan ej vara tomt',
    vehicle: 'Fordon',
    vehicles: 'Fordon',
    vehicleTypes: 'Fordonstyper',
    vehicleUser: 'Brukare',
    veryHot: 'Stekhet',
    visit: 'Kundbesök',
    visitingAddress: 'Besöksadress',
    waitingForCompanyOrder: 'Väntar på ledningsuppgifter',
    waitingForNameOrder: 'Väntar på personuppgifter',
    waitingForPhoneOrder: 'Väntar på telefonnummer',
    waitingForMailingsOrder: 'Väntar på brevutskick',
    whatIsBilprospekt: 'Vad är bilprospekt',
    willCall: 'Skall ringa',
    willEmail: 'Skall e-posta',
    willMail: 'Skall e-posta',
    willMeeting: 'Skall ha möte',
    willPost: 'Skall skicka brev',
    with: 'Med',
    won: 'Vunnen',
    years: 'År',
    zipMuncipality: 'Postort'
}
