export default {
    aboutUs: 'Om oss',
    action: 'Händelse',
    activities: 'Aktiviteter',
    activitiesComingUp: 'Ej utförda aktiviteter',
    activity: 'Aktivitet',
    addComment: 'Lägg till kommentar',
    addFile: 'Bifoga fil',
    address: 'Adress',
    agile: 'Bearbeta',
    allActivitiesAllIncludingComments: 'Alla händelser och kommentarer',
    analyse: 'Analysera',
    analysis: 'Behovsanalys',
    at: 'Hos',
    calendar: 'Kalender',
    calendarMonths: {
        1: 'Januari',
        2: 'Februari',
        3: 'Mars',
        4: 'April',
        5: 'Maj',
        6: 'Juni',
        7: 'Juli',
        8: 'Augusti',
        9: 'September',
        10: 'Oktober',
        11: 'November',
        12: 'December',
    },
    call: 'Samtal',
    cancel: 'Avbryt',
    cars: 'Fordon',
    changedOwner: 'Ändrad ansvarig',
    cold: 'Kall',
    comment: 'Kommentar',
    comments: 'Kommentarer',
    companyInfo: 'Företagsinformation',
    complete: 'Utförd',
    completeEvent: 'Aktivitet utförd',
    connectCars: 'Koppla fordon',
    connectContacts: 'Koppla kontaktpersoner',
    connectedTo: 'Kopplad till',
    connectKoncernCompanies: 'Koppla koncern-företag',
    connectProspects: 'Koppla prospekt',
    contact: 'Kontakt',
    contacts: 'Kontaktpersoner',
    contacted: 'Behov undersöks',
    contactInfo: 'Kontaktinformation',
    contactWasRemoved: 'Kontakten har tagits bort',
    contactWasSaved: 'Ny kontakt sparad',
    contactWasUpdated: 'Kontakten har ändrats',
    couldNotGetDeal: 'Kunde ej hämta affär',
    created: 'Skapad',
    createNewContact: 'Skapa ny kontakt',
    createNewPassword: 'Skapa nytt lösenord',
    dataMissing: 'Uppgift saknas',
    date: 'Datum',
    deal: 'Affär',
    dealWasUpdated: 'Affären är nu uppdaterad',
    descriptionDeal: 'Beskrivning av affär',
    didCall: 'Har ringt',
    didEmail: 'Har e-postat',
    didLosePrice: 'Förlorade affären pga. pris',
    didLoseProduct: 'Förlorade affären pga. produkten',
    didLoseUnknown: 'Förlorade affären pga. okänd anledning',
    didLoseWindow: 'Förlorade affären pga. prospektet inte var i köpfönstret',
    didMail: 'Har e-postat',
    didMeeting: 'Har haft möte',
    didPost: 'Har skickat brev',
    doVehicleSearch: 'Gör fordonssökning',
    download: 'Ladda ner',
    edit: 'Redigera',
    editComment: 'Redigera kommentar',
    editContact: 'Redigera kontakt',
    editDeal: 'Redigera affär',
    emailNotifications: 'E-post notifikationer',
    entityWasAddedToContact: 'Koppling till kontakt har skapats',
    entityWasRemovedFromContact: 'Kopplingen för kontakt har tagits bort',
    events: 'Planerade aktiviteter',
    eventsCalendar: 'Kalendervy',
    eventsFlow: 'Flödesvy',
    female: 'Kvinna',
    files: 'Filer',
    for: 'För',
    from: 'Från',
    gender: 'Kön',
    genderNotProvided: 'Kön ej angivet',
    handleCars: 'Hantera fordon som är kopplade till affären',
    handleContacts: 'Redigera kontaktpersoner',
    handleFiles: 'Hantera uppladdade filer',
    handleProspects: 'Hantera prospekt som är kopplade till affären',
    hideConnectCars: 'Dölj koppla fordon',
    hideConnectContacts: 'Dölj koppla kontaktpersoner',
    hideConnectProspects: 'Dölj koppla prospekt',
    home: 'Hem',
    hot: 'Het',
    iceCold: 'Iskall',
    idle: 'Prospekt',
    imgTextLogo: 'Bilprospekt logotyp',
    lastUpdate: 'Senast uppdaterad',
    lists: 'Listor',
    load: 'Ladda fler',
    login: 'Inloggning',
    logon: 'Logga in',
    logout: 'Logga ut',
    lost: 'Förlorad',
    lukewarm: 'Ljummen',
    mail: 'E-post',
    male: 'Man',
    maturity: 'Affärens sannolikhet',
    maximize: 'Maximera',
    meeting: 'Möte',
    minimize: 'Minimera',
    move: 'Flytta',
    moved: 'Flyttade',
    name: 'Namn',
    navigateBefore: 'Bakåt',
    navigateNext: 'Framåt',
    navigateToCar: 'Gå till fordon',
    navigateToProspect: 'Gå till prospekt',
    negotiation: 'Under förhandling',
    news: 'Nyheter',
    newsSub: 'Detta har hänt på Bilprospekt.se',
    noActivity: 'Aktivitet saknas',
    noCars: 'Fordon saknas',
    noContacts: 'Kontakter saknas',
    noEvents: 'Ingen planerad aktivitet',
    noFiles: 'Inga uppladdade filer',
    noProspects: 'Prospekt saknas',
    notProvided: 'Ej angivet',
    offer: 'Offert',
    offert: 'Offert',
    on: 'På',
    onDeal: 'På affär',
    oneProspect: 'Prospekt',
    openInAgile: 'Öppna i Bearbeta',
    other: 'Övrigt',
    ourService: 'Vår tjänst',
    owner: 'Ansvarig',
    parentCompany: 'Moderbolag',
    phone: 'Telefon',
    placeholderSearchAll: 'Sök person, företag eller registreringsnummer...',
    placeholderSearchCars: 'Sök fordon av denna brukare...',
    placeholderSearchKoncernCompanies: 'Sök företag inom koncern...',
    placeholderSearchContacts: 'Sök kontakt...',
    potential: 'Potential',
    prices: 'Priser',
    prospect: 'Prospektera',
    prospects: 'Prospekt',
    regarding: 'Gällande',
    regret: 'Återställ',
    regNumber: 'Registreringsnummer',
    remove: 'Ta bort',
    removeCar: 'Ta bort fordon',
    removeComment: 'Ta bort kommentar',
    removeContact: 'Radera kontakt',
    removeEnsure: 'Är du säker?',
    removeEntityFromContact: 'Ta bort kontaktens koppling till detta objekt',
    removeEvent: 'Ta bort planerad aktivitet',
    removeProspect: 'Ta bort prospekt',
    responsible: 'Ansvarig',
    save: 'Spara',
    saveChanges: 'Spara ändringar',
    saveContact: 'Spara ny kontakt',
    savedInList: 'Sparad i lista',
    savePassword: 'Spara lösenord',
    search: 'Sök',
    settings: 'Inställningar',
    settingsPasswordHintEmpty: 'Lösenord kan ej vara tomma',
    settingsPasswordHintNotMatching: 'Lösenorden överensstämmer ej',
    settingsPasswordHintSaved: 'Nytt lösenord sparat',
    status: 'Status',
    team: 'Team',
    theDeal: 'Affären',
    theTeam: 'Vi som jobbar här',
    testride: 'Provkörning',
    time: 'Tid',
    to: 'Till',
    todo: 'I kontakt',
    toggleComments: 'Visa/dölj kommenterar',
    toggleMoved: 'Visa/dölj förflyttningar',
    toggleOff: 'Av',
    toggleOn: 'På',
    trash: 'Borttagen',
    unknown: 'Okänd',
    uploadFile: 'Ladda upp fil',
    user: 'Användare',
    valuation: 'Värdering',
    veryHot: 'Stekhet',
    visit: 'Kundbesök',
    willCall: 'Skall ringa',
    willEmail: 'Skall e-posta',
    willMail: 'Skall e-posta',
    willMeeting: 'Skall ha möte',
    willPost: 'Skall skicka brev',
    with: 'Med',
    won: 'Vunnen',
    years: 'År',
    zipMuncipality: 'Postort'
}
