export const agileActionTypes = {
    SET_ALL_PROSPECTS_RECEIVED: 'SET_ALL_PROSPECTS_RECEIVED',
    SET_COLUMNS: 'SET_COLUMNS',
    SET_FILTERS: 'SET_FILTERS',
    SET_PREVIEW_DATA: 'SET_PREVIEW_DATA',
    SET_PREVIEW_ID: 'SET_PREVIEW_ID',
    SET_SORT: 'SET_SORT',
};
